INT-6261 - Ingest XMCyber entities
JupiterOne/graph-xmcyber pull request #1
Opened 2022-12-08 14:27 UTC by dobregons

# Description

This PR adds the basic integration for XMCyber and contains:
- Handle auth verification
- Ingest `xmcyber_entity` and handle paginated requests
- Handle rate limit based on response headers
- Add tests and recordings
- Contains docs/spes

### Notes
- Missing to define relevant questions

## Type of change

Please leave any irrelevant options unchecked.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### General Development Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### Integration Development Checklist:

Please leave any irrelevant options unchecked.

- [x] I have checked for additional permissions required to call any new API
      endpoints, and have documented any additional permissions in
      `jupiterone.md`, where necessary.
- [x] My changes properly paginate the target service provider's API
- [x] My changes properly handle rate limiting of the target service provider's
      API
- [ ] My new integration step is instrumented to execute in the correct order
      using `dependsOn`
- [ ] I have referred to the
      [JupiterOne data model](https://github.com/JupiterOne/data-model/tree/main/src/schemas)
      to ensure that any new entities/relationships, and relevant properties,
      match the recommended model for this class of data
- [x] I have updated the `CHANGELOG.md` file to describe my changes
- [ ] When changes include modifications to existing graph data ingestion, I've
      reviewed all existing managed questions referencing the entities,
      relationships, and their property names, to ensure those questions still
      function with my changes.

2022-12-08 15:10 UTC, zemberdotnet commented on src/steps/constants.ts
> +    _class: ['Entity'],
I think these should be `_class: ['Record']` from the data model.

2022-12-08 15:17 UTC, dobregons commented on src/steps/constants.ts
> +    _class: ['Entity'],
Yes, you're right, I'll change it. Thank you!

2022-12-08 18:13 UTC, zemberdotnet commented on src/client.ts
> +        this.logger.info(
I like your rate limiting implementation. While it should guard us from hitting the rate limit, I would still include a backup explicit handling of  `status: 429`. If we ever do accidental hit a rate limit would shouldn't fail. However, right now I think it would get caught on line 176 and throw an error. Let me know if I missed something.

2022-12-08 21:18 UTC, VDubber commented on src/steps/entities/converter.ts
> +        discoveredAt: entity.discoveredAt,
If `discoveredAt` is a date, the pattern we follow is: `discoveredOn`. 

We also have a util to parse dates into a common format: `parseTimePropertyValue`

2022-12-08 23:02 UTC, dobregons commented on src/client.ts
> +        this.logger.info(
Yes, you're right, if we receive a `status: 429` it'd throw an error, but that's something I'm trying to avoid with the implementation of this function `checkRateLimitStatus` so I think that would not be possible, and if that happens, an error will be thrown which means that it's an unhandled rate limit and we'd need to fix it.

2022-12-08 23:31 UTC, VDubber requested changes

2022-12-08 23:31 UTC, VDubber commented on jupiterone/questions/questions.yaml
> +    title: What xmcyber entities are choke points?
xmcyber -> XM Cyber

From a quick google, looks like `XM Cyber` is preferred over `XMCyber`

2022-12-08 23:31 UTC, VDubber commented on src/client.ts
> +  public async fetchEntities(page: number, pageSize: number) {
Could this be a private method?

2022-12-08 23:31 UTC, VDubber commented on src/client.ts
> +export function createXMCyberClient(
We should consider making this a singleton so that the rateLimitStatus state can be shared. Not necessary with only a single entity being ingested so maybe just a TODO comment. Or you can just knock it out :)

2022-12-08 23:31 UTC, VDubber commented on src/steps/entities/converter.ts
> +        affectedAssetsCount: entity.affectedAssets.count.value,
Safe to always access these values?

2022-12-08 23:31 UTC, VDubber commented on src/steps/entities/converter.ts
> +        assetOn: parseTimePropertyValue(entity.assetAt),
👍

2022-12-08 23:31 UTC, VDubber commented on src/steps/entities/converter.ts
> +        labels: JSON.stringify(entity.labels),
What is the structure of this data?

2022-12-08 23:31 UTC, VDubber commented on src/steps/entities/converter.ts
> +        labels: JSON.stringify(entity.labels),
Arrays of strings are supported by the system

2022-12-08 23:31 UTC, VDubber commented on src/client.ts
> +        this.logger.info(
A lot of times we handle rate limiting in both scenarios. If, for example, the customer is hitting the provider  API at the same time we are, our rate limit status data may not be as accurate as we hope. The provider API would end up throwing a 429. 

This [package](https://github.com/lifeomic/attempt) is one we often use to make retries and error handling easier. Which we should add to the .request() method below. If we get a 500 error, for example, we should try it again.

2022-12-08 23:31 UTC, VDubber commented on src/client.ts
> +      throw new IntegrationProviderAPIError({
Add retry logic. see above comment.

2022-12-08 23:44 UTC, dobregons commented on src/client.ts
> +        this.logger.info(
Nice, I'll implement the retry logic, thanks for the suggestion.

2022-12-08 23:45 UTC, dobregons commented on src/steps/entities/converter.ts
> +        affectedAssetsCount: entity.affectedAssets.count.value,
Yes, I think so, these "affectedAssets" or "affectedEntities" counts are the main values that our client wants to use to query.

2022-12-12 20:50 UTC, VDubber reviewed
A few comments but ready to approve if you don't see it necessary to make those changes.

2022-12-12 20:50 UTC, VDubber commented on src/steps/entities/converter.ts
> +        tags: JSON.stringify(entity.tags),
Should `tags` follow the same pattern as `labels` above?

2022-12-12 21:04 UTC, VDubber commented on src/steps/entities/converter.ts
> +        tags: JSON.stringify(entity.tags),
A JSON string isn't very friendly to queries. What if we map to: `[key:value, key:value]` to make it queryable?

2022-12-12 21:17 UTC, VDubber approved these changes

2022-12-12 21:23 UTC, merged

2022-12-12 21:38 UTC, j1-internal-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v1.0.0`](https://github.com/JupiterOne/graph-xmcyber/releases/tag/v1.0.0) :rocket: